language:
  - php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit --coverage-text

after_script:
  #- php vendor/bin/coveralls
  # or enable logging
  - php vendor/bin/coveralls -v

